package de.pfannekuchen.lotas.savestate;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.util.List;

/**
 * Used to keep track of savestates and rerecordings
 * @author Pancake
 */
public class TrackerFile {
	
	// This is the worst Code I have ever written.
	
	public static void increaseSavestates(final File savestateDir, final String worldName) throws IOException {
		final File infoFile = new File(savestateDir, worldName + "-info.txt");
		generateFile(infoFile, readSavestates(savestateDir, worldName) + 1, readLoadstates(savestateDir, worldName));
	}
	
	public static void increaseLoadstates(final File savestateDir, final String worldName) throws IOException {
		final File infoFile = new File(savestateDir, worldName + "-info.txt");
		generateFile(infoFile, readSavestates(savestateDir, worldName), readLoadstates(savestateDir, worldName) + 1);
	}
	
	public static int readSavestates(final File savestateDir, final String worldName) throws IOException {
		final File infoFile = new File(savestateDir, worldName + "-info.txt");
		if (!infoFile.exists()) {
			infoFile.createNewFile();
			generateFile(infoFile, 0, 0);
			return -1;
		}
		List<String> lines = Files.readAllLines(infoFile.toPath());
		return Integer.parseInt(lines.get(3).split("=")[1]);
	}
	
	public static int readLoadstates(final File savestateDir, final String worldName) throws IOException {
		final File infoFile = new File(savestateDir, worldName + "-info.txt");
		if (!infoFile.exists()) {
			infoFile.createNewFile();
			generateFile(infoFile, 0, 0);
			return -1;
		}
		List<String> lines = Files.readAllLines(infoFile.toPath());
		return Integer.parseInt(lines.get(4).split("=")[1]);
	}
	
	private static void generateFile(final File file, final int savestates, final int loadstates) throws FileNotFoundException {
		PrintWriter writer = new PrintWriter(file); // Empty File
		writer.println("");
		writer.close();
		
		PrintWriter hwga = new PrintWriter(file);
		hwga.print("# This file was generated by TASmod/LoTAS and diplays info about the usage of savestates\r\n\r\n\r\n");
		hwga.println("Total Savestates=" + savestates);
		hwga.println("Total Rerecords=" + loadstates);
		hwga.close();
	}
	
}
