name: Compile LoTAS

on:
  push:
    branches: [ "dev" ]

jobs:
  fabric:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.repository == 'MinecraftTAS/LoTAS'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: remapJar --no-daemon
          gradle-version: 8.5
          cache-disabled: true
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LoTAS
          path: build/libs/*.jar
      - name: Upload to discord
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: build/libs/*.jar
