name: Compile Fabric
run-name: Compile LoTAS for all Minecraft Versions

on:
  push:
    branches: [ "dev-3.0.0", "workflow"]

jobs:
  fabric:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Prepare build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: prepBase --no-daemon
        gradle-version: 8.0.2
        cache-disabled: true
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: buildCi --no-daemon
        gradle-version: 8.0.2
        cache-disabled: true
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: LoTAS
        path: build/collect/*.jar
    - name: Zip artifacts
      uses: montudor/action-zip@v1
      with:
        args: zip -r LoTAS.zip build/libs/*
    - name: Upload to discord
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: LoTAS.zip
